# Module manifest for module 'VisualEffects'
# Generated by: Arnoud Jansveld
# Generated on: 2023-10-16
@{
    RootModule         = 'VisualEffects.psm1'
    ModuleVersion      = '1.0.6'
    GUID               = '7b649cfe-4868-47e1-ba36-e10647278215'
    Author             = 'Arnoud Jansveld'
    CompanyName        = 'Jane Street'
    Copyright          = '(c) 2025 Jane Street. All rights reserved.'
    Description        = 'Manage Windows visual effects'
    # RequiredModules    = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess   = @()
    # TypesToProcess     = @()
    # FormatsToProcess   = @()
    # NestedModules      = @()
    FunctionsToExport  = @(
        'Get-VisualEffect'
        'Set-VisualEffect'
        'Get-VisualEffectPreset'
        'Set-VisualEffectPreset'
	)
    CmdletsToExport    = @()
    VariablesToExport  = @()
    AliasesToExport    = @()
    # ModuleList         = @()
    # FileList           = @()
    PrivateData        = @{
        PSData = @{
            Tags                       = @('Windows', 'VisualEffects', 'Visual_Effects', 'PSEdition_Core',
                                           'PSEdition_Desktop')
            LicenseUri                 = 'https://github.com/janestreet/VisualEffects/blob/master/LICENSE.md'
            ProjectUri                 = 'https://github.com/janestreet/VisualEffects'
            # IconUri                    = ''
            # ReleaseNotes               = ''
            # Prerelease                 = ''
            # ExternalModuleDependencies = @()
        } # End of PSData hashtable
    } # End of PrivateData hashtable
    # HelpInfoURI        = ''
}
